### ISSUE TITLE
Hyphenate in small viewports only

### ISSUE THREAD

**Issue by mnater** [mnater/Hyphenopoly#53]
Got mail from V.:

Find a way to support something like:
````css
h1.hyphenate { hyphenate: no; } 

@media screen and (max-width: 300px){
    h1.hyphenate { hyphenate: yes; } 
}
````
